### ISSUE TITLE
NoSuchMethodError in 1.8.9-2.0.3 crashes dedicated Forge Server 1.8.9 b1764 on startup

### ISSUE THREAD

**Issue by kreezxil** [jaredlll08/Fluxed-Core#3]
`[20:37:35] [Server thread/ERROR] [FML]: Failed to save extended properties for fluxedcore.  This is a mod issue.
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]: java.lang.NoSuchMethodError: net.minecraft.nbt.NBTTagCompound.setTag(Ljava/lang/String;Lnet/minecraft/nbt/NBTBase;)V
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at fluxedCore.entity.EntityData.saveNBTData(EntityData.java:22)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.entity.Entity.func_70109_d(Entity.java:1377)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.entity.Entity.func_70039_c(Entity.java:1332)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75820_a(AnvilChunkLoader.java:345)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_75816_a(AnvilChunkLoader.java:165)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.world.gen.ChunkProviderServer.func_73242_b(ChunkProviderServer.java:238)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.world.gen.ChunkProviderServer.func_73151_a(ChunkProviderServer.java:298)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:905)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:366)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:398)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:534)
[20:37:35] [Server thread/INFO] [STDERR]: [net.minecraft.entity.Entity:func_70109_d:1382]:      at java.lang.Thread.run(Thread.java:745)
`

**Comment by kreezxil** [comment]
Yes it crashed hard enough to not actually generate a log file.

**Comment by jaredlll08** [comment]
Try the latest version please

**Comment by jaredlll08** [comment]
1.8 is no longer supported. 1.8.9 is nearly a year / 3 versions old now, it is time to move on. This action was performed via a bot, if it was done in error, please contact Jaredlll08 immediately

**Comment by kreezxil** [comment]
I love it when programmers tell folks to move on. As a modpack designer I make packs across all breaches.

-----Original Message-----

**Comment by jaredlll08** [comment]
uh yea, that is fine and easy for you, but when I have to support 4 mc versions, it gets difficult.

**Comment by kreezxil** [comment]
Semantics really, point is just say you don't support xxx instead of telling folks to move on. Which sounds way better. 

-----Original Message-----

**Comment by jaredlll08** [comment]
eh, I guess you are right, I'll update the bot
